### ISSUE TITLE
error adding binary sensor

### ISSUE THREAD

**Issue by kuradi** [HASwitchPlate/openHASP-custom-component#101]
## Version of the custom_component

latest. also latest ha

## Describe the bug
cant add binary sensor

## Debug log

Error while setting up openhasp platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/openhasp/binary_sensor.py", line 34, in async_setup_entry
    [
  File "/config/custom_components/openhasp/binary_sensor.py", line 35, in <listcomp>
    HASPBinarySensor(
  File "/config/custom_components/openhasp/binary_sensor.py", line 58, in __init__
    self._attr_name = f"{name} binary_sensor {self._gpio}"
AttributeError: 'HASPBinarySensor' object has no attribute '_gpio'

**Comment by Joraeim** [comment]
I had this same issue. You can add the following line to the _init_ function for the HASPBinarySensor class just prior to line 58 to resolve this error.

`self._gpio = gpio`

 (This may not completely fix it, I'm having a separate error at the same time.)

**Comment by htvekov** [comment]
Has this issue with the binary sensor been resolved ?
Didn't really notice that my sensors in HA was no longer available as I use MQTT in HA to trigger on GPIO  events from the plates

**Comment by dgomes** [comment]
yes in ea2a04e049ddb59b5b0981d52560c8a902a185a6

**Comment by htvekov** [comment]
Updated CC to ea2a04e -> All OK

**Comment by kuradi** [comment]
> yes in [ea2a04e](https://github.com/HASwitchPlate/openHASP-custom-component/commit/ea2a04e049ddb59b5b0981d52560c8a902a185a6)

excuse me but what should i do to get rid of this error? i have latest 0.6.6 installed....

**Comment by htvekov** [comment]
> excuse me but what should i do to get rid of this error? i have latest 0.6.6 installed....

openHASP CC 0.6.6 still has this binary sensor issue.
Switch to main branch, redownload and restart HA. Now your CC should be commit 45a4e44 and have working binary sensors in HA

![image](https://user-images.githubusercontent.com/45469813/203641434-cc25df4f-78e9-4604-97c2-ffb092b4ed4b.png)
