### ISSUE TITLE
Homeassistant Mqtt Discovery not working

### ISSUE THREAD

**Issue by richardpt86** [HASwitchPlate/openHASP-custom-component#104]
My plate was not being discovered by the integration.
Looking at the logs openHasp was configuring MQTT discovery at "hasp/discovery"
Updating the /config/custom_components/openhasp/manifest.json file to listen on "hasp/discovery/#" fixed the issue.

**Comment by dgomes** [comment]
You are using a beta version of the firmware and the stable version of the custom component

Hopefully we will release 0.7.0 soon :)

**Comment by fvanroie** [comment]
Both the firmware `master` and `main` branch of the CC have been updated to version 0.7.0.
Please update to the latest commits which should fix discovery.
