### ISSUE TITLE
Remove the need to restart HA to load configuration changes for openHASP

### ISSUE THREAD

**Issue by matsekberg** [HASwitchPlate/openHASP-custom-component#108]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Rather than restarting HA when changes to the openHASP config has been made, the alternative "reload all yaml configuration" should be sufficient for the openHASP integration to reload the config.

**Describe alternatives you've considered**
Se above

**Additional context**
None

**Comment by schafran** [comment]
On the integration page under settings, have you tried reloading the custom component instead?
OpenHASP integration > three dots > reload

**Comment by fvanroie** [comment]
@matsekberg Does this resolve your issue?

**Comment by matsekberg** [comment]
I haven’t tried that yet but it might, I will check.

**Comment by fvanroie** [comment]
Closed. Feel free to comment if the issue still persists.
