### ISSUE TITLE
Setup failed for custom integration openhasp

### ISSUE THREAD

**Issue by gromitn** [HASwitchPlate/openHASP-custom-component#109]
Hi

I have just upgraded to HA Operating System 10.2 (from 10.1) and HA started I get:

```
Logger: homeassistant.setup
Source: setup.py:214
First occurred: 9:04:20 AM (1 occurrences)
Last logged: 9:04:20 AM

Setup failed for custom integration openhasp: Unable to import component: Exception importing custom_components.openhasp
```

I cannot restart HA as it fails the config check:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/__init__.py:563
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:07:06 AM (1 occurrences)
Last logged: 9:07:06 AM

[140586943335056] The system cannot restart because the configuration is not valid: Component error: openhasp - Exception importing custom_components.openhasp
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1849, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1889, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 563, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Component error: openhasp - Exception importing custom_components.openhasp
```

How do I go about fault finding this?

I have disabled openHASP in the integrations, but this hasn't helped.

Appreciate any pointers!!

**Comment by ziocharly** [comment]
Problem also here:
after HA 10.2 update, the openHASP integration (0.7.0) do not discover anymore my openHasp device (WT32-SC01 - V.0.6.3)...
Do you have any solutions ?

**Comment by fvanroie** [comment]
> Do you have any solutions ?

Update the device to v0.7.0 or downgrade the integration to 0.6.6... Both need to be on the same version level.

**Comment by gromitn** [comment]
If I have disabled openHASP, can I safely ignore the config check and force a HA restart?

**Comment by fvanroie** [comment]
It seems you have a yaml error in `openhasp.yaml`. The Custom Component works fine with HA 10.2 here.

**Comment by fvanroie** [comment]
We added a [Pre-Release 0.7.2](https://github.com/HASwitchPlate/openHASP-custom-component/releases/tag/0.7.2) with support for HA 2024.1. Please help test it before release by redownloading this version of the Custom Component in HACS.
