### ISSUE TITLE
No discvery for wt32-sc01-plus_16MB

### ISSUE THREAD

**Issue by pauldogg** [HASwitchPlate/openHASP-custom-component#116]
Similar / relevant
https://github.com/HASwitchPlate/openHASP/discussions/445#discussioncomment-8348998

I have a wt32-sc01-plus_16MB that will not become discovered; and therefore cannot be setup in home assistant.

openhasp 0.7.0-rc10 fb2bebf

HACS version 1.34.0
I've tried changing openHASP to 0.7 (from 0.6.3) also 0.7.1, rebooted the device and home assistant with no discovery...

MQTT shows as connected in the information tab of the device.

MQTT
Server | XX.XX.XX.XXX
Username | XXXXX
Client ID | plate_36b164
Status | Connected
Received
Published | 32
Failed

Display with the UI  on the device seems to work fine.

Pages.json:

{"page":1,"id":1,"obj":"btn","x":0,"y":0,"w":240,"h":30,"text":"openHASP","value_font":22,"bg_color":"#2C3E50","text_color":"#FFFFFF","radius":0,"border_side":0}
{"page":1,"id":2,"obj":"btn","x":10,"y":40,"w":105,"h":90,"toggle":true,"text":"\uE335","text_font":32,"mode":"break","align":1}
{"page":1,"id":3,"obj":"dropdown","x":10,"y":140,"w":170,"h":30,"options":"Apples\nBananas\nOranges\nMelon"}
{"page":0,"id":1,"obj":"label","x":175,"y":5,"h":30,"w":62,"text":"00.0°C","align":2,"bg_color":"#2C3E50","text_color":"#FFFFFF"}

openhasp.yaml:

plate35:
objects:
- obj: "p0b1" # temperature label on all pages
properties:
"text": '{{ states("sensor.my_room_temperature") }}°C'
- obj: "p1b2" # light-switch toggle button
properties:
"val": '{{ 1 if states("light.my_room") == "on" else 0 }}'
"text": '{{ "\uE6E8" if is_state("light.my_room", "on") else "\uE335" | e }}'
event:
"up":
- service: homeassistant.toggle
entity_id: "light.my_room"
- obj: "p1b3" # dropdown
event:
"changed":
- service: persistent_notification.create
data:
message: I like {{ text }}

Any help would be greatly appreciated.
Thanks

**Comment by MikeJoss** [comment]
I got mine to discover by removing the plate from the openhasp.yaml.  With anything in there about this plate it would not dioscover.
I have two of these plates, leaving the first one's config in openhasp.yaml was fine.
Removed all the config for the second one, restarted HA and restarted the plate and it discovered.

Hope that helps.

**Comment by MikeJoss** [comment]
Oh, and after that, if you get an error starting the integration, make sure you have put the config for it back into openhasp.yaml and restart the integration.

**Comment by fvanroie** [comment]
We've added ùDNS discovery in the lastest nightly build of the firmware and 0.7.2-RC of the Custom Component.
This should fix the issues with delayed discovery.

**Comment by TheITGeorge** [comment]
Thank kinda worked for me, I was running the stable 6.6 on homeassistant and my 2 wt32-sc01-plus_16MB where not detected in openhasp, while looking in MQTT with MQTT explorer I saw that they creating topics.
But after upgrading to 0.7.2-RC they are detected however they are not working.

Openhasp give me on both sc01's a error "no devices or entries" 

![Screenshot_20240316_234540_Home Assistant](https://github.com/HASwitchPlate/openHASP-custom-component/assets/39765824/3ca629b3-1878-4098-a8a8-13a8dfc826b7)

I already tried reboot HA, the SC01's, removing there configuration from openhasp.yaml 

My old Lanbon L8 is still running fine (on firmware 0.6.3)

**Comment by TheITGeorge** [comment]
It turned out in my case it was a user error... i made a typo... twice... 😅
I called my screens CS01 and CS02, and in the config i accidentally typed in SC01 and SC02, i guess it was very late for me.
But after correcting the names in the config and rebooting HA it all started to work 🥳

**Comment by fvanroie** [comment]
Can this issue be closed now?
