### ISSUE TITLE
Latest release (0.7.2) clashes with latest firmware release (0.6.3)

### ISSUE THREAD

**Issue by akloeckner** [HASwitchPlate/openHASP-custom-component#124]
I have installed the latest releases of both the custom component (0.7.3) and the firmware (0.6.3). At least to my understanding. And this produces the warning about non-matching versions. I am happy to ignore this warning for some more years, if need be. However, I wonder if I am missing something:

Is there an 0.7.x release of the firmware? Or should I stick to the 0.6.x release of the custom component?

**Comment by fvanroie** [comment]
You can get 0.7.0 of the firmware at https://nightly.openhasp.com

**Comment by akloeckner** [comment]
Thanks, I knew I missed something...
