### ISSUE TITLE
MQTT discovery not working

### ISSUE THREAD

**Issue by Sonusss** [HASwitchPlate/openHASP-custom-component#141]
Using HA 2024.4.4 
OpenHasp custom component 0.7.4
Plate firmware 0.6.2

I have several plates which are working well.
Cannot add an extra plate which is correclty configured.

I can see the discovery message on the MQTT broker
`hasp/discovery {"node":"plate_0","mdl":"Lanbon L8","mf":"openHASP","hwid":"98f4ab87566c","pages":12,"sw":"0.6.2","input":{},"power":[],"light":[12,14,27],"dim":[]}`

Nothing special reported in the logs

I tried also with plate firmware 0.6.3 and got the same problem

**Comment by fvanroie** [comment]
You need  Plate firmware 0.7.x

**Comment by fvanroie** [comment]
There is no release, only release candidate at this point. You can build it from source, download from the [Actions tab](https://github.com/HASwitchPlate/openHASP-custom-component/actions) or https://nightly.openhasp.com

**Comment by Sonusss** [comment]
I compiled the latest plate version openHASP 0.7.0-rc12
I can see the discovery message:
`hasp/discovery/98f4ab87566c {"node":"plate_0","mdl":"Lanbon L8","mf":"openHASP","hwid":"98f4ab87566c","pages":12,"sw":"0.7.0-rc12","node_t":"hasp/plate_0/","uri":"http://10.10.1.95","input":{},"power":[],"light":[12,14,27],"dim":[],"event":[]}
`
But still no discovery for this one.
This hardware was used before as another plate, might this be the problem, MAC Address or something ?
But I deleted the plate config in HA custom component before doing anything.

Another brand new plate was perfectly discovered...

**Comment by fvanroie** [comment]
You *really* need to remove _every_ reference in HA before it will discover a previously seen plate...

**Comment by Sonusss** [comment]
I spent a lot of time trying this without success...
The only workaround I found is deleting the whole database which is a pity as  trashing all history.

**Comment by fvanroie** [comment]
Good to see you have managed to add the plate again. I'm not sure what was the issue but from other feedback this seems to work normally:

> You need to remove all references of the plate in HA
> Then restart HA and then the plate
