### ISSUE TITLE
Release 0.7.4 is reported  as Version 0.7.2

### ISSUE THREAD

**Issue by rmkew377** [HASwitchPlate/openHASP-custom-component#145]
I installed Release 0.7.4 because HomeAssistant   throwed Warning about detected blocking call
The new version (downloaded as .ZIP) seemed to fix this.
But: the Addon says it is Version 0.7.2 though.
manifest.json of Release 0.7.4 contains the element:
    "version": "0.7.2",  
Is that the reason? 

 
## Version of the custom_component
0.7.4 ( hopefully;) )

**Comment by fvanroie** [comment]
0.7.5 is released
