### ISSUE TITLE
plate does not get discovered by openhasp

### ISSUE THREAD

**Issue by supermarcie** [HASwitchPlate/openHASP-custom-component#152]
My plate was previously detected, but after deleting it in openhasp it does not detect anymore

version of openhasp in HA 0.7.6
version of firmware on plate : 0.7.0-rc12 96f9e70

configuration.yaml

openhasp:
  platetest123:

debug logging is on but this does not shows anything about the discovery, my second plate is not online and the log only shows that he can not go to a certain page.

I already removed the second plate and it is detected without any issue, but other plate not.
Also removed the openhasp addon, but this alo did not helped.
In the MQQT explorer I see the discovery entry of my plate, but does not show up in openhasp.
So please let me know what I can do to get it working again

**Comment by fvanroie** [comment]
For other users that encounter this situation: [How do you UN-ignore a device?](https://community.home-assistant.io/t/how-do-you-un-ignore-a-device/526641)
