### ISSUE TITLE
Feature request: separate backlight level setting for awake and idle

### ISSUE THREAD

**Issue by nagyrobi** [HASwitchPlate/openHASP-custom-component#37]
Backlight level currently only has one slider, which acts on the awake level. 
A bit confusing though that the slider position goes down to the value of idle brightness, when the plate is idle - the slider is _showing_ the actual brightness value, whilst it's _setting_ the awake brightness level.

As we had earlier in the component config, we could offer a way to configure default levels:
- _max_ backlight level, default for awake if not set manually
- _min_ backlight level, default for idle if not set manually

To impose some practical constraints for accidental or unwanted settings (one may drag the slider to 0 and then misunderstand why the screen turned off completely; max limit would help the owner to save for long-term burn-in or power consumption).

This would require two separate sliders, either by implementing two virtual lights, or alternatively by re-using some other property of light component like `white_value` (maybe not a good idea as it may conflict with other stuff in HA).

**Comment by nagyrobi** [comment]
The `min` and the `max` levels could be simply set in ` brightness = ranged_value_to_percentage((0, 255), self._brightness)` instead of 0 and 255.

Thus the slider would work only between min and max not 0 and 255.

**Comment by fvanroie** [comment]
I'm ok with changing the dim values from 0-100 to 0-255 too. This is more in line with other gpio led levels.

**Comment by dgomes** [comment]
the awake brightness was a concept from the initial version... 

currently its a "previous brightness" meaning the value to which brightness will be restored when the plate awaken.

I don't think setting the awake brightness provides a good UX, depending on the time of the day I would like to have a different level...

**Comment by dgomes** [comment]
to avoid turning off (dim 0) I think I will limit the brightness to 1 (it is done in other light integrations)

**Comment by fvanroie** [comment]
Maybe the firmware need to interpret dim=0 as light=off to avoid confusion? That way, dim can never go to 0.

**Comment by nagyrobi** [comment]
No I think we should leave firware handle 0 as zero, as most lamps do it like this.

**Comment by dgomes** [comment]
I'm confused... how do we proceed @fvanroie ?

**Comment by fvanroie** [comment]
Make the firmware 0-255 and limit CC to 1-255 dim level. I think that covers all possibilities.

**Comment by dgomes** [comment]
OK! When you push that change, please reference this issue, so I can implement the change :)

**Comment by dgomes** [comment]
I think we can close this now https://github.com/HASwitchPlate/openHASP-custom-component/commit/2d9fb24333f31b26946d0b4f55b6374763fcf76a
