### ISSUE TITLE
Add a version check

### ISSUE THREAD

**Issue by fvanroie** [HASwitchPlate/openHASP-custom-component#46]
**Is your feature request related to a problem? Please describe.**

To improve clarity, we could implement a warning message when the CC version get out-of-sync with the firmware version of a plate.

**Describe the solution you'd like**

Can the CC check the HASP version in statusupdate at start?
Could it warn about incompatible plate versions? i.e. different *major.minor*  version

**Describe alternatives you've considered**

Keeping the plate and CC versions in sync can be tough and currently it isn't obvious to the user.
Since the plates can be any version and the HA CC is central, all plates should be checked to be in line with the current CC version.

**Additional context**

n/a

**Comment by dgomes** [comment]
Done in e39213ba65a74fc91e79ce5c8ac2d5351292a537

**Comment by fvanroie** [comment]
Great, thanks!
