### ISSUE TITLE
Feature request: Entity offline handling

### ISSUE THREAD

**Issue by nagyrobi** [HASwitchPlate/openHASP-custom-component#58]
**Is your feature request related to a problem? Please describe.**
Make more exact the way HA is handling plate entities when they are unreachable on the network, in order for the user to be able to correctly identify which plate has problems and fix the correct one.

**Describe the solution you'd like**
Currently only switch/light entities go to `Unavailable` state when plate goes off the network. Main entity should also turn to `Unavailable`.
In HA > Configuration > Integrations where the plates are listed a notification icon should be present (just like when config slug is missing currently) at the plates which are offline (a yellow triangle with exclamation mark would be good). This way the user can immediately be aware which one(s) need fixing.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by fvanroie** [comment]
I checked and I think this is working correctly now in 0.7.0. Please check again.
