### ISSUE TITLE
Services integration documentation links not working

### ISSUE THREAD

**Issue by fvanroie** [HASwitchPlate/openHASP-custom-component#70]
## Version of the custom_component
v0.6.2

## Describe the bug
In Developer Tools > Services:

The integration documentation help links point to https://www.home-assistant.io/integrations/openhasp instead of the openHASP documentation.

## Debug log

![image](https://user-images.githubusercontent.com/15969459/131425622-e769c1b6-3e2a-4cf4-8898-80ad2ee08527.png)

**Comment by dgomes** [comment]
Unfortunately can't control that link... :(

**Comment by fvanroie** [comment]
Oh I think I understand now... it's because we are using HACS?
That link is pointing to the official integrations repository, which we don't have (yet).

**Comment by dgomes** [comment]
This has been fixed upstream :)

**Comment by fvanroie** [comment]
Great, thanks @dgomes !
