### ISSUE TITLE
Adapt to changed mqtt.async_publish in HA core 2021.12 #166

### ISSUE THREAD

**Issue by dgomes** [HASwitchPlate/openHASP-custom-component#76]
mqtt.async_publish is a couroutine in HA core 2021.12: home-assistant/core#58441

This requires minimum version of HA to 2021.12.0.

**Comment by fvanroie** [comment]
Tested and no issues here.

**Comment by nagyrobi** [comment]
All fine here too in this regard.

**Comment by dgomes** [comment]
fixed in 7a22d8e070cc6621ecf9a53b80b0d1c94e99285a
