### ISSUE TITLE
Feature request: A few more config options

### ISSUE THREAD

**Issue by nagyrobi** [HASwitchPlate/openHASP-custom-component#77]
Just like Antiburn, please expose a few more configuration entities to HA:
- page number as `input_number` (box mode, min/max set to 0/12)
- long idle as `input_number` (box mode, 0/3600)
- short idle as `input_number` (box mode, 0/3600)
- reboot as `switch`

Idles for example, would make life a little easier in [things like this](https://haswitchplate.github.io/openHASP-docs/0.6.2/integrations/home-assistant/sampl_autom/#keep-backlight-on-dimmed-during-the-day-and-turn-it-off-during-the-night), when we want to dynamically change the idle modes based on day/night/lightsensor/etc.

**Comment by nagyrobi** [comment]
Also I think it would be appropriate to expose _Idle brightness_ too as an adjustable value at run time (perhaps with an `input_number` with min/max as 0/255) instead of having it as only a fixed value chosen during setup.

The use case is when the screen doesn't turn off completely, just dims out. This dimmed brightness should be possible to be adjusted in corelation with the environment brightness (based on external information from sensors, light sources being on or off, or sun coming in or not through the window.

**Comment by dgomes** [comment]
just pushed a commit with page number

I don't have any command to setup long_idle and short_idle....

**Comment by nagyrobi** [comment]
What do you mean by that?
See [system commands](https://haswitchplate.github.io/openHASP-docs/0.6.2/commands/#system-commands).

Like:
```
    - service: mqtt.publish
      data:
        topic: hasp/plates/config/gui
        payload: '{"idle2":0}'
```

**Comment by dgomes** [comment]
I was referring to "normal" commands and not gui configuration... (like we use for antiburn)

**Comment by nagyrobi** [comment]
These are all normal commands actually, they take effect immediately and very useful.

**Comment by dgomes** [comment]
added restart as a button

(still think idle should be command and not a configuration...) @fvanroie

**Comment by fvanroie** [comment]
Reboot and pagenumber works fine. Let me look into idle...

**Comment by fvanroie** [comment]
In the future `idle` could have a JSON payload where the keys are optional e.g. `{"state":"long","idle1":60,"idle2":120}`
but that would be a breaking change meaning it's reserved for `0.7.x`
