### ISSUE TITLE
YAML support for the JSONL files

### ISSUE THREAD

**Issue by danielo515** [HASwitchPlate/openHASP-custom-component#80]
**Is your feature request related to a problem? Please describe.**
No, not a problem

**Describe the solution you'd like**
I see that the configuration file for the plate can be written in plain JSON, that will then be translated to JSONL: https://haswitchplate.github.io/openHASP-docs/0.6.2/integrations/home-assistant/howto/#json-files

My immediate question was: why not YAML too? Since the plugin already translates from JSON to JSONL and it is possible to translate from yaml to JSON I see no reason why this could not be possible.

**Describe alternatives you've considered**
Nothing really

**Additional context**
The advantages of this is that YAML is less verbose and easier to write by hand than JSON

**Comment by fvanroie** [comment]
Is this something that you are able to work on yourself? Otherwise I am inclined to close this issue, since JSON/JSONL is equally easy to use.
