### ISSUE TITLE
switch.plate_antiburn unavailable

### ISSUE THREAD

**Issue by RazoredRaven** [HASwitchPlate/openHASP-custom-component#85]
Not sure why it's not showing as "unavailable", maybe because I'm running the latest HA (2021.12.3)

Didn't even realise this switch was implemented, very keen to try it out but it's not working currently.

Hardware: Lanbon L8-HD.

**Comment by nagyrobi** [comment]
Remove and re-add the plate from the system.

**Comment by fvanroie** [comment]
@RazoredRaven Did this fix the issue with antiburn?

**Comment by RazoredRaven** [comment]
I removed and re-added 3 of the plates. Only 1/3 of the plates has the "antiburn" switch as functional. The rest show up as "unavailable".

**Comment by fvanroie** [comment]
This is probably related to issue #94.

**Comment by dgomes** [comment]
fixed in [0.6.5](https://github.com/HASwitchPlate/openHASP-custom-component/releases/tag/0.6.5)
