### ISSUE TITLE
Page number entity

### ISSUE THREAD

**Issue by nagyrobi** [HASwitchPlate/openHASP-custom-component#89]
## Version of the custom_component

917615d

## Configuration

N/A

## Describe the bug
After this fix: https://github.com/HASwitchPlate/openHASP-custom-component/issues/88
Number entity experiences the following symptoms:
- After reloading the integrattion the entity remains unavailable. To fix, need to restart plate.
- Restarting the plate doesn't go back to the page it was before restart, instead, jumps to page 1. This happens even if integration is not reloaded (just change to any other page and restart the plate, after connecting back, it will show page 1 and number will update to 1). Earlier the plate restored the page it was on, before reboot, which was very convenient.

## Debug log

N/A

**Comment by dgomes** [comment]
should be fixed in `main`

**Comment by dgomes** [comment]
fixed in [0.6.5](https://github.com/HASwitchPlate/openHASP-custom-component/releases/tag/0.6.5)
