### ISSUE TITLE
Detected code that uses str (config) for entity category

### ISSUE THREAD

**Issue by xtimmy86x** [HASwitchPlate/openHASP-custom-component#91]
Hi to all, after the last update of Home Assistant Core 2022.1

the custom integration generate an error on Log:

"Detected code that uses str (config) for entity category. This is deprecated and will stop working in Home Assistant 2022.4, it should be updated to use EntityCategory instead. Please report this issue."

With previous core versione 2021 it's all perfect

**Comment by fvanroie** [comment]
It seems the be related to this line in the code:
https://github.com/HASwitchPlate/openHASP-custom-component/blob/762e55fbe1cf8815a1d56ed2a5f55e94d40b79be/custom_components/openhasp/config_flow.py#L48

**Comment by dgomes** [comment]
It's actually https://github.com/HASwitchPlate/openHASP-custom-component/blob/762e55fbe1cf8815a1d56ed2a5f55e94d40b79be/custom_components/openhasp/config_flow.py#L62

**Comment by fvanroie** [comment]
Ha! Just to show I don't know a thing about the HA python CC api's 🤣

**Comment by dgomes** [comment]
fixed in [0.6.5](https://github.com/HASwitchPlate/openHASP-custom-component/releases/tag/0.6.5)
