### ISSUE TITLE
error after update to HA 2022.06

### ISSUE THREAD

**Issue by xtimmy86x** [HASwitchPlate/openHASP-custom-component#99]
After updating home assistant to 2022.06 version there is an error in the log:

Detected integration that uses deprecated `async_get_registry` to access device registry, use async_get instead. Please report issue to the custom component author for openhasp using this method at custom_components/openhasp/__init__.py, line 247: device_registry = await dr.async_get_registry(hass)

**Comment by nagyrobi** [comment]
This is not an error, it's a warning, the component still works properly.
Will be fixed in the next release.
